[package]
name = "aoc"
version = "0.1.0"
edition = "2021"

[lib]
name = "aoc"
path = "src/lib.rs"

[dependencies]
regex = "1"
itertools = "0.13.0"
clap = { version = "4.5", features = ["derive", "string"] }
serde_json = "1.0"
fxhash = "0.2"
