[project]
name = "aoc"
version = "0.1.0"
description = "Solvers for Advent of Code"
requires-python = ">=3.12"
dependencies = [
    "tabulate>=0.8.9",
]

[tool.black]
line-length = 120

[tool.isort]
profile = "black"

[tool.ruff]
fix=true
